title: "Stat 850 Project"
author: "Ryan Lalicker, Carson Trego"
bibliography: references.bib

project:
  output-dir: _output
  render:
    - guidelines.qmd
    - proposal.qmd
    - report.qmd
    - slides.qmd
    - README.md

execute:
  echo: false
  message: false
  warning: false

toc: true
number-sections: true
