---
title: "Stat 850 Project Proposal"
format: html
editor: visual
---

## Instructions

Each member of your team should modify this document in some way and push their modifications to the repository in a separate commit. This will ensure that you have set your repository up in a way that ensures all group members are working with the same repository.

Please ensure that you have set your git name and email address on your computer by **modifying** the following commands and running them in the terminal:

    git config --global user.name "____ ____"
    git config --global user.email "______@unl.edu"

In the proposal as in the final report, all of your code chunks should be set so that `echo = F`, which prevents the code from being printed in the report. You should also set `message = F, warning = F`, which will reduce the amount of additional output which is present in the report. You can customize the execution of code in quarto by using additional options, some of which are detailed [here](https://quarto.org/docs/computations/execution-options.html).

## Data

### Source

The data we are using in this project comes from the U.S. Energy Information Administration (EIA) official website. This information is not openly available and requires an API key registration to access (The data was converted to a CSV and will be posted for this project).

To access the data we used, you can either view the CSV we have created, or access the information yourself using the API.

> 1\) Go to the official EIA website at eia.gov/opendata/
>
> 2\) select electricity and go to generation
>
> 3\) under generation, select "includes monthly generation by fuel type, sector, and state"
>
> 4\) after following the link, go under "API ROUTE" and set select route to "Electricity", then below that select "Electric Power Operations (Annual And Monthly)"
>
> 5\) under "FREQUENCY", set "select frequency" to "monthly" and do not fill in the optional start and end parameters.
>
> 6\) under "DATA TYPE", hit "select all"
>
> 7\) finally, hit submit to get your API URL and header.
>
> Once you have the information provided from this search and your API key, you should be able to run the following code:

```{python}
import requests
import json
import pandas as pd
from skimpy import skim

# API KEY
api_key = 'YOU NEED A KEY'

#API URL
apiUrl = "https://api.eia.gov/v2/electricity/electric-power-operational-data/data/?frequency=monthly&data[0]=ash-content&data[1]=consumption-for-eg&data[2]=consumption-for-eg-btu&data[3]=consumption-uto&data[4]=consumption-uto-btu&data[5]=cost&data[6]=cost-per-btu&data[7]=generation&data[8]=heat-content&data[9]=receipts&data[10]=receipts-btu&data[11]=stocks&data[12]=sulfur-content&data[13]=total-consumption&data[14]=total-consumption-btu&sort[0][column]=period&sort[0][direction]=desc&offset=0&length=5000"

#Combined API URL and API key, will be used as a single input inton the api function
urlAndKey = f"{apiUrl}&api_key={api_key}"

# HEADER, an input to the api
headers = {
    "X-Params": json.dumps({
        "frequency": "monthly",
        "data": [
            "ash-content",
            "consumption-for-eg",
            "consumption-for-eg-btu",
            "consumption-uto",
            "consumption-uto-btu",
            "cost",
            "cost-per-btu",
            "generation",
            "heat-content",
            "receipts",
            "receipts-btu",
            "stocks",
            "sulfur-content",
            "total-consumption",
            "total-consumption-btu"
        ],
        "facets": {},
        "start": None,
        "end": None,
        "sort": [
            {
                "column": "period",
                "direction": "desc"
            }
        ],
        "offset": 0,
        "length": 5000 #ADJUSTABLE; WILL EXTEND WHEN I GET MORE SPACE MY COMPUTER IS MELTING
    })
}

# GET REQUEST, as stated in the EIA method section
response = requests.get(urlAndKey, headers=headers)

# Response Status code (200 = success)
if response.status_code == 200:
    data = response.json()  # read response
else:
    print(f"REQUEST FAILED---CODE: {response.status_code}")
    print(response.text) 



df1=pd.DataFrame(data)
df1=pd.DataFrame(data['response']['data'])
df1.head()
skim(df1)
```

### Description

This dataset contains information about monthly annual and monthly power operations by state, sector, and energy source. If includes things like ash content, heat content, sulfur content, and amount of power generated.

It was collected from power sources around the country by the EIA.

**CARSON\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\-\--**

Here is a data dictionary showing each variable, the type of variable, units, and range of values that are possible:

SOME SIGNIFICANT RANGE OUTLIERS ARE TO BE NOTED

SOME UNITS ARE INCOMPLETE, IN TERMS OF NEEDING A NUMERATOR

| Name                   | Description                                                               | Type      | Units                              | Range/Values         |
|-----------|------------------|-----------|-----------|---------------------|
| sectorid               | Number id associated with the sector inn question                         | numeric   | NA                                 | 0 - 99               |
| ash-content            | Average ash content of consumed fuel                                      | numeric   | percent                            | 0 - 60%              |
| consumption-for-eg     | Consumption of Fuels for Electricity Generation (Physical Units)          | numeric   | \<Variable\> Physical Unit         | 0-650,000 Units      |
| consumption-for-eg-btu | Consumption of Fuels for Electricity Generation (BTUs)                    | numeric   | Million MMBTU                      | 0-1300 Million MMBTU |
| consumption-uto        | Consumption of Fuels for Useful Thermal Output (physical units)           | numeric   | \<Varaible\> Physical Unit         | 0-130,000 Units      |
| consumption-uto-btu    | Consumption of Fuels for Useful Thermal Output (BTU)                      | numeric   | Million MMBTU                      | 0-160 Million MMBTU  |
| cost                   | Average Cost of Fuels (per Physical Unit)                                 | numeric   | \<Variable\> Physical Unit         | 0-160                |
| cost-per-btu           | Average Cost of Fuels (per BTU)                                           | numeric   | Million MMBTU                      | 0-29                 |
| generation             | Utility Scale Electricity Net Generation                                  | numeric   | GWh                                | -330-280             |
| heat-content           | Average Heat Content of Consumed Fuels                                    | numeric   | BTU/Physical Unit                  | 0-39                 |
| receipts               | Receipts of Fuel\[?\] (physical units)                                    | numeric   | \<Variable\> Physical Unit         | 0-600000             |
| receipts-per-btu       | Reciepts of Fuel\[?\] (BTUs)                                              | numeric   | Million MMBTU                      | 0-760000             |
| Stocks                 | Stocks of Fuel (Physical Units)                                           | numeric   | thousand\<Variable\> Physical Unit | 0-29000              |
| sulfur-content         | Average Sulfur Content of Consumed Fuel                                   | numeric   | Percent                            | 0-5.9                |
| total-consumption      | Consumption of Fuels for Electricity Generation and Useful Thermal Output | numeric   | \<Variable\> Physical Unit         | 0-690000             |
| total-consumption-btu  | Consumption of Fuels for Electricity Generation and Useful Thermal Output | numeric   | Million MMBTU                      | 0-1400               |
| FuelTypeId             | Type of fuel                                                              | character | \-                                 | \-                   |
| SectorId               | Id of the "sector" where the generation is performed                      | character | \-                                 | \-                   |

## Project Goals

Describe why this data is interesting and what you hope to do with it.

We will use the dataset to explore the following topics:

-   How much of the energy produced is renewable.

-   Sulfur content in different fuel types.

-   Ash content in different fuel types.

We expect to create:

-   Normal Q-Q plot to test for normality
-   Relative frequency histograms to visually observe distibutions
-   Residuals vs. fitted model plot to check for nonlinearity
-   May include a multiple regression model

## Division of Labor

60/40 Carson for R coding.

60/40 Ryan for writing

We hope to have the graphs done and the paper mostly written by Thanksgiving break. Additionally we hope to have many slides completed and a script started by that time.

## Additional Comments

We think this data could potentially provide some challenges. If they are too difficult we may change our project if that is allowed.
